import type { Metadata } from "next";
import "./globals.css";
import { Taskbar } from "../Components/Taskbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Taskbar/>
        <main className="m-auto h-[calc(100vh-96px)] min-w-[300px] max-w-full lg:h-[calc(100vh-96px)]">
          {children}
        </main>
      </body>
    </html>
  );
}
