import type { Metadata } from "next";
import "./globals.css";
import { Taskbar } from "../Components/Taskbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Taskbar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
